/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeepgramHeader {
        /**
          * The active site
         */
        "active": 'playground' | 'console' | 'docs' | 'community';
        /**
          * Boolean to toggle debug mode
         */
        "debug": boolean;
        /**
          * Boolean to track if the menu is open
         */
        "isMenuOpen": boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "is-menu-open"?: boolean;
    }
}
declare global {
    interface HTMLDeepgramHeaderElement extends Components.DeepgramHeader, HTMLStencilElement {
    }
    var HTMLDeepgramHeaderElement: {
        prototype: HTMLDeepgramHeaderElement;
        new (): HTMLDeepgramHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "deepgram-header": HTMLDeepgramHeaderElement;
    }
}
declare namespace LocalJSX {
    interface DeepgramHeader {
        /**
          * The active site
         */
        "active"?: 'playground' | 'console' | 'docs' | 'community';
        /**
          * Boolean to toggle debug mode
         */
        "debug"?: boolean;
        /**
          * Boolean to track if the menu is open
         */
        "isMenuOpen"?: boolean;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "is-menu-open"?: boolean;
    }
    interface IntrinsicElements {
        "deepgram-header": DeepgramHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deepgram-header": LocalJSX.DeepgramHeader & JSXBase.HTMLAttributes<HTMLDeepgramHeaderElement>;
        }
    }
}
